### ISSUE TITLE
Excessive Logging

### ISSUE THREAD

**Issue by mitchelljkotler** [Moesif/moesifdjango#47] opened 2021-02-09 19:13 UTC
After installing the Moesif middleware, I got the following polluting my logs every 5 seconds:
```
INFO 2021-02-09 18:50:49,865 base 4 139721478100736 Running job "Schedule events batch job every 5 second (trigger: interval[0:00:05], next run at: 2021-02-09 18:50:49 UTC)" (scheduled at 2021-02-09 18:50:49.858046+00:00)
INFO 2021-02-09 18:50:50,228 base 4 139721478100736 Job "Schedule events batch job every 5 second (trigger: interval[0:00:05], next run at: 2021-02-09 18:50:54 UTC)" executed successfully
```
It also appears during interactive sessions.

I believe the following line is overriding the configuration of other loggers:
https://github.com/Moesif/moesifdjango/blob/master/moesifdjango/middleware.py#L33

**Comment by keyur9** [comment] 2021-02-09 22:54
Hello, @mitchelljkotler! Thanks for letting us know. We've fixed the issue in version 1.7.7. Let us know if you're still having issues.

**Comment by mitchelljkotler** [comment] 2021-02-10 18:59
Thank you for the very quick response.  I updated to version 1.7.8 and I no longer see the logging in the interactive sessions, but my app server logs still are receiving the following message constantly:
`INFO 2021-02-10 18:58:16,814 base 7422 140513091137664 Added job "Schedule events batch job every 5 second" to job store "default"`

**Comment by keyur9** [comment] 2021-02-11 05:20
Hello @mitchelljkotler, We're running with Celery and using moesifdjango 1.7.8 and we're not seeing any INFO log. Would you mind sharing more information about your setup (Logging framework/config Celery/something else, Django/Celery version, etc) so that we could reproduce it on our end?

**Comment by mitchelljkotler** [comment] 2021-02-15 15:11
My logging configuration:
```
  LOGGING = {                                                                                                                                                                                                                                            
      "version": 1,                                                                                                                                                                                                                  
      "disable_existing_loggers": True,                                                                                                                                                                                                                              
      "formatters": {                                                                                                                                                                                                   
          "verbose": {                                                                                                                                                                                                                                                  
              "format": "%(levelname)s %(asctime)s %(module)s "                                                                                                                                                                                               
              "%(process)d %(thread)d %(message)s"                                                                                                                                                                                 
          }                                                                                                                                                                                                                                     
      },                                                                                                                                                                                                                                                   
      "handlers": {                                                                                                                                                                                                                    
          "console": {                                                                                                                                                                                                                                           
              "level": "DEBUG",                                                                                                                                                                                                  
              "class": "logging.StreamHandler",                                                                                                                                                                                                          
              "formatter": "verbose",                                                                                                                                                                                                                
          }                                                                                                                                                                                                        
      },                                                                                                                                                                                                                                                      
      "root": {"level": "INFO", "handlers": ["console"]},                                                                                                                                                                               
      "loggers": {                                                                                                                                                                                                                                        
          "django.db.backends": {
              "level": "ERROR",
              "handlers": ["console"],                                                                                                                                                                                                                   
              "propagate": False,                                                                                                                                                                                                                             
          },                                                                                                                                                                                                                                                         
          # Errors logged by the SDK itself                                                                                                                                                                             
          "sentry_sdk": {"level": "ERROR", "handlers": ["console"], "propagate": False},                                                                                                                                                                              
          "django.security.DisallowedHost": {                                                                                                                                                                                                         
              "level": "ERROR",                                                                                                                                                                                                    
              "handlers": ["console"],                                                                                                                                                                                                          
              "propagate": False,                                                                                                                                                                            
          },                                                                                                                                                                                               
      },                                                                                                                                                                                 
  } 
```

Django v2.2.5
Celery v4.4.2

App servers have the following logs:
`INFO 2021-02-15 15:04:07,481 base 29145 140491669835904 Added job "Schedule events batch job every 5 second" to job store "default"`
`WARNING 2021-02-15 15:04:08,401 base 29059 140491490469632 Execution of job "Schedule events batch job every 5 second (trigger: interval[0:00:05], next run at: 2021-02-15 15:04:08 UTC)" skipped: maximum number of running instances reached (1)`
Celery beat host has the following log:
`[2021-02-15 15:02:36,522: WARNING/MainProcess] Job "Schedule events batch job every 5 second (trigger: interval[0:00:05], next run at: 2021-02-15 15:02:41 UTC)" raised an exception`
These messages show up between 3 - 15 second intervals.

I am also seeing the following uncaught exception in my Sentry logs hundreds of times a day:
```APIException: HTTP response not OK.
  File "moesifdjango/tasks.py", line 83, in async_client_create_event
    batch_events_api_response = api_client.create_events_batch(batch_events)
  File "moesifapi/controllers/api_controller.py", line 136, in create_events_batch
    self.validate_response(_context)
  File "moesifapi/controllers/base_controller.py", line 39, in validate_response
    raise APIException("HTTP response not OK.", context)
```
I also see the following handled exception in my sentry logs about a dozen times a day:
```
Error submitting job "<Job (id=moesif_events_batch_job name=Schedule events batch job every 5 second)>" to executor "default"
RuntimeError: cannot schedule new futures after shutdown
  File "apscheduler/schedulers/base.py", line 979, in _process_jobs
    executor.submit_job(job, run_times)
  File "apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "concurrent/futures/thread.py", line 117, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
```

Also, let me know if it would make sense to move this discussion to a support ticket rather than GitHub issues.

**Comment by mitchelljkotler** [comment] 2021-02-16 16:33
Another error thrown from the moesif task:
```
RuntimeError: dictionary changed size during iteration
  File "apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "moesifdjango/tasks.py", line 132, in <lambda>
    func=lambda: async_client_create_event(moesif_events_queue, config, config_etag, last_updated_time),
  File "celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "celery/local.py", line 109, in _get_current_object
    return loc(*self.__args, **self.__kwargs)
  File "celery/app/__init__.py", line 72, in task_by_cons
    return app.tasks[
  File "kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "celery/app/base.py", line 1272, in tasks
    self.finalize(auto=True)
  File "celery/app/base.py", line 544, in finalize
    for task in values(self._tasks):
 ```

**Comment by dgilling** [comment] 2021-02-16 17:52
Thanks for the additional info @mitchelljkotler, let us take a look.

**Comment by keyur9** [comment] 2021-02-18 00:01
Hello, @mitchelljkotler! Thanks for sharing additional information. We've fixed the issue and released version 2.0.0. Let us know if you're still having issues.

**Comment by mitchelljkotler** [comment] 2021-02-19 15:25
Thanks for the continued quick responses.  This seems to fix most of the issues, however, I still get the following error about 10-20 times a day:
```
Error submitting job "<Job (id=moesif_events_batch_job name=Schedule events batch job every 2 second)>" to executor "default"

RuntimeError: cannot schedule new futures after shutdown
  File "apscheduler/schedulers/base.py", line 979, in _process_jobs
    executor.submit_job(job, run_times)
  File "apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "concurrent/futures/thread.py", line 117, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
```

**Comment by dkm199** [comment] 2021-02-19 23:41
@mitchelljkotler can you try 2.0.1 and let us know what you observe?  I am also curious whats your application lifecycle looks like, did your application restart several times when you noticed above error 10-20 times.

**Comment by mitchelljkotler** [comment] 2021-02-23 14:49
I updated to 2.0.1 yesterday and have not seen any errors since.  Thank you!  As for my application lifecycle, I did not see any application restarts correlating to the above error.

**Comment by dkm199** [comment] 2021-02-25 00:43
Thanks for the update. closing now. Please feel free to reopen if needed

**Closed by dkm199** 2021-02-25 00:43 UTC
